### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RodrigoDiazC** [RodrigoDiazC/PreNomina#1]
-[ ] Disable detailed view table ordering
-[ ] Multi selection on registers and days
-[ ] "No tomar en cuenta" feature on each register
-[ ] Fix unhandled exception when first two columns in preliminar view ar double clicked
-[ ] Change "Seleccionar directorio" to "Guardar en"

**Comment by RodrigoDiazC** [comment]
Major fixes/features
- [x] Department selection in options window
- [ ] Add department to excel file
- [ ] Add all configurations in options window to configuration file
- [ ] File history
- [ ] "No tomar en cuenta" feature on each register
- [ ] Multi selection on registers and days
